// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bturdenxhyvpumnlpfot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0dXJkZW54aHl2cHVtbmxwZm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MjM2MTIsImV4cCI6MjA3MDE5OTYxMn0.tlM2SZEc4lq6xUYS4UbDMP8851OT2XQXO7mBRPFSO50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});